[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml",
]

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 16

[colors]
draw_bold_text_with_bright_colors = true
