" .vimrc

" Load all Vim-Plug modules
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'

" visuals
Plug 'morhetz/gruvbox'
Plug 'itchyny/lightline.vim' | Plug 'maximbaz/lightline-ale'
Plug 'junegunn/limelight.vim'
Plug 'chrisbra/colorizer'

" editing
Plug 'scrooloose/nerdcommenter'
Plug 'roxma/vim-paste-easy'
Plug 'tpope/vim-surround'
Plug 'danro/rename.vim'

" navigating
Plug 'christoomey/vim-tmux-navigator'

" languages
Plug 'w0rp/ale'
Plug 'hashivim/vim-terraform'

" ai
Plug 'Exafunction/windsurf.vim', { 'branch': 'main' }

" building
Plug 'tpope/vim-dispatch'

" git/github
Plug 'tpope/vim-fugitive'
Plug 'mattn/webapi-vim' | Plug 'mattn/gist-vim'
call plug#end()

" editing defaults
set nowrap " stop word wrapping
set clipboard=unnamedplus " use full system clipboard
set number relativenumber " enable number gutter with relative line numbers
set list listchars=tab:▸\ ,eol:¬ " set 'invisible' characters
set spell spelllang=en_us " enable spell check
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab " default is 4
let mapleader="\<SPACE>" " leader key

" filetypes
augroup FileTypes
  autocmd!
  autocmd FileType markdown setlocal wrap
  autocmd FileType javascript,json,yaml setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType make setlocal ts=4 sts=4 sw=4 noexpandtab
augroup END

" shortcuts
" return to last opened file
nmap <Leader><Leader> <c-^>
" tab to next buffer
nnoremap <Tab> :bnext!<CR>
" shift tab to previous buffer
nnoremap <S-Tab> :bprev!<CR>
nnoremap <Leader>ev :e ~/.vim/vimrc<CR>
nnoremap <Leader>sv :source ~/.vim/vimrc<CR>
" remove highlighting
nnoremap <Leader>nh :noh<CR>

" centralize backups, swapfiles and undo history
set backupdir=~/.vim/tmp/backup
set directory=~/.vim/tmp/swap
if exists("&undodir")
    set undodir=~/.vim/tmp/undo
endif

" ignore some files and directores
if has("wildmenu")
    set wildmode=longest,list
    if has ("wildignore")
        set wildignore+=.hg,.git,.svn
        set wildignore+=*.a,*.o,*.obj,*.exe,*.dll,*.pyc
        set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
        set wildignore+=.DS_Store,.git,.hg,.svn
        set wildignore+=*~,*.swp,*.tmp
    endif
endif

" colorscheme
colorscheme gruvbox
set termguicolors
syntax enable

" vim-lightline
let g:lightline = {}
let g:lightline.colorscheme = 'one'
let g:lightline.component_expand = {
  \  'linter_checking': 'lightline#ale#checking',
  \  'linter_infos': 'lightline#ale#infos',
  \  'linter_warnings': 'lightline#ale#warnings',
  \  'linter_errors': 'lightline#ale#errors',
  \  'linter_ok': 'lightline#ale#ok',
  \ }
let g:lightline.component_type = {
  \  'linter_checking': 'right',
  \  'linter_infos': 'right',
  \  'linter_warnings': 'warning',
  \  'linter_errors': 'error',
  \  'linter_ok': 'right',
  \ }
let g:lightline.active = { 
  \  'left': [
    \  ['mode', 'paste'],
    \  ['readonly', 'relativepath', 'modified']
    \ ],
  \  'right': [
    \  [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_infos', 'linter_ok' ],
    \  [ ],
    \  [ 'lineinfo', 'filetype', ],
    \ ]
  \ }
let g:lightline.inactive = { 
  \  'left': [[ 'relativepath', ]],
  \  'right': [[ 'percent', ]],
  \ }
let g:lightline#ale#indicator_checking  = "⟳"
let g:lightline#ale#indicator_ok        = "✔"
let g:lightline#ale#indicator_infos     = "»"
let g:lightline#ale#indicator_warnings  = "▲"
let g:lightline#ale#indicator_errors    = "✘"

" limelight
nmap <Leader>ll :Limelight!!<CR>
xmap <Leader>ll :Limelight!!<CR>

" grep
set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
set grepformat=%f:%l:%c:%m

" ale
let g:ale_set_signs = 1
let g:ale_completion_enabled = 0
let g:ale_lint_on_text_changed = 'never'

" gist
let g:gist_post_private = 1
let g:gist_clip_command = 'pbcopy'

" Open current GH file in browser using the ghcli
command GHBrowse silent! execute "!gh browse " . expand('%:h') . "/" . expand('%:t') . ":" . line('.')

set exrc
set secure
