" .vimrc

" Load all Vim-Plug modules
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'

" visuals
Plug 'altercation/vim-colors-solarized'
Plug 'itchyny/lightline.vim'

" editing
Plug 'roxma/vim-paste-easy'
Plug 'tpope/vim-surround'
Plug 'preservim/nerdcommenter'

" navigating
Plug 'christoomey/vim-tmux-navigator'
call plug#end()

" editing defaults
set nowrap " stop word wrapping
set clipboard=unnamedplus " use full system clipboard
set number relativenumber " enable number gutter with relative line numbers
autocmd InsertEnter * set norelativenumber
autocmd InsertLeave * set relativenumber
set list listchars=tab:▸\ ,eol:¬ " set 'invisible' characters
set spell spelllang=en_us " enable spell check
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab " default is 4
let mapleader="\<SPACE>" " leader key

" filetypes
augroup FileTypes
  autocmd!
  autocmd FileType markdown setlocal wrap
  autocmd FileType javascript,json,yaml setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType make setlocal ts=4 sts=4 sw=4 noexpandtab
augroup END

" shortcuts
" return to last opened file
nmap <Leader><Leader> <c-^>
" tab to next buffer
nnoremap <Tab> :bnext!<CR>
" shift tab to previous buffer
nnoremap <S-Tab> :bprev!<CR>
nnoremap <Leader>ev :e ~/.vim/vimrc<CR>
nnoremap <Leader>sv :source ~/.vim/vimrc<CR>
" remove highlighting
nnoremap <Leader>nh :noh<CR>

" centralize backups, swapfiles and undo history
if !isdirectory(expand("~/.vim/tmp/backup"))
  call mkdir(expand("~/.vim/tmp/backup"), "p")
  call mkdir(expand("~/.vim/tmp/swap"), "p")
  call mkdir(expand("~/.vim/tmp/undo"), "p")
endif
set backupdir=~/.vim/tmp/backup
set directory=~/.vim/tmp/swap
set undodir=~/.vim/tmp/undo

" ignore some files and directores
if has("wildmenu")
    set wildmode=longest,list
    if has ("wildignore")
        set wildignore+=.hg,.git,.svn
        set wildignore+=*.a,*.o,*.obj,*.exe,*.dll,*.pyc
        set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
        set wildignore+=.DS_Store
        set wildignore+=*~,*.swp,*.tmp
    endif
endif

" push yank register to pbcopy on mac
augroup YankToMacClipboard
  autocmd!
  autocmd TextYankPost * if v:event.operator is 'y' && v:event.regname == '' |
        \ call system('pbcopy', getreg('"')) |
        \ endif
augroup END

" colorscheme
colorscheme solarized
set background=dark
syntax enable

" vim-lightline
let g:lightline = {}
let g:lightline.colorscheme = 'one'
let g:lightline.active = { 
  \  'left': [
    \  ['mode', 'paste'],
    \  ['readonly', 'relativepath', 'modified']
    \ ],
  \  'right': [
    \  [ 'lineinfo', 'filetype', ],
    \ ]
  \ }
let g:lightline.inactive = { 
  \  'left': [[ 'relativepath', ]],
  \  'right': [[ 'percent', ]],
  \ }

" grep
set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
set grepformat=%f:%l:%c:%m

" Open current GH file in browser using the ghcli
command GHBrowse silent! execute "!gh browse " . expand('%:h') . "/" . expand('%:t') . ":" . line('.')

set exrc
set secure
