#!/bin/sh

# only install/init oh-my-zsh if the directory doesn't already exist
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    # install oh my zsh
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
# install bullet-train theme
curl -sfLo "$HOME/.oh-my-zsh/custom/themes/bullet-train.zsh-theme" \
    --create-dirs \
    https://raw.githubusercontent.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme
# install zsh-nvm plugin
curl -sfLo "$HOME/.oh-my-zsh/custom/plugins/zsh-nvm/zsh-nvm.plugin.zsh" \
    --create-dirs \
    https://raw.githubusercontent.com/lukechilds/zsh-nvm/master/zsh-nvm.plugin.zsh
